name: edit_distance
description: Implementation of string distance algorithms.
version: 0.3.0
author: Kwang Yul Seo <email@example.com>
homepage: https://github.com/kseo/edit_distance

environment:
  sdk: '>=1.8.0 <2.0.0'

dependencies:
  quiver_iterables: ^1.0.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
